application:
  port: 8000
  host: 127.0.0.1
database:
  adapter: "postgres"
  host: "localhost"
  port: 5432
  username: "ninja"
  password: "n!nj4d8"
  db_name: "newsletter"
  test_db_prefix: "test_newsletter_"